name: desertweb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"
  

flutter_launcher_icons:
  web:
    generate: true
    image_path: "lib/Assets/c-removebg-preview.png"
    background_color: "#fffffff"
    theme_color: "#fffffff"

flutter:
  uses-material-design: true
