name: todo_list_mobile_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_plus: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  path: ^1.8.3  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
